### PR TITLE
ARTEMIS-4435 Add missing MANIFEST.MF content for Artemis artifacts.

### PR DESCRIPTION
**Pull request by soul2zimate**
(cherry picked from commit 3392d084a904f9517a30242facb0159cf94fbc87)
Issue: https://issues.redhat.com/browse/JBEAP-25217

LTS 7.10 ENTMQBR issue: https://issues.redhat.com/browse/ENTMQBR-8551

Upstream issue: https://issues.apache.org/jira/browse/ARTEMIS-4435 and https://issues.apache.org/jira/browse/ARTEMIS-4477

Upstream PR: https://github.com/apache/activemq-artemis/pull/4625 and https://github.com/apache/activemq-artemis/pull/4658

### CODE REVIEW

**Comment by brusdev** [comment]
@soul2zimate what is the ENTMQBR issue?
https://issues.redhat.com/browse/ENTMQBR

**Comment by soul2zimate** [comment]
Hi @brusdev It's https://issues.redhat.com/browse/ENTMQBR-8551

**Comment by brusdev** [comment]
Hi @soul2zimate, I see that [ARTEMIS-4435](https://issues.apache.org/jira/browse/ARTEMIS-4435) is causing [ARTEMIS-4477](https://issues.apache.org/jira/browse/ARTEMIS-4477), could you review it and eventually add the related commits to this PR?

**Comment by soul2zimate** [comment]
sure, I will check that issue.

**Comment by soul2zimate** [comment]
I have picked that fix as well. Thanks for the heads up

**Review by brusdev — APPROVED** [review]

**Pull request merged**
