### PR TITLE
Backport ARTEMIS-3045 ReplicationManager can batch sent replicated packets

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/ENTMQBR-8284 backport https://issues.apache.org/jira/browse/ARTEMIS-3045 to 2.16.0.jbossorg-eap-x branch for EAP 7.4 CP.

This would fix an issue in Artemis when we upgrade Netty to 4.1.94.Final in EAP 7.4. Please find more information in JBEAP issue https://issues.redhat.com/browse/JBEAP-25261

### CODE REVIEW

**Comment by gaol** [comment]
Thanks @soul2zimate to bring this up :+1: 

@franz1981 would you please review ? thanks !

**Comment by jbertram** [comment]
Franz doesn't work on AMQ anymore so he won't be able to review this PR.

This looks fine to me. What do you think @clebertsuconic?

**Comment by soul2zimate** [comment]
@jbertram Thank you for the review.

Hi @clebertsuconic May I ask your review and merge ?

**Comment by gaol** [comment]
@clebertsuconic EAP 7.4.13 has been frozen, it is a blocker for us to proceed with the Netty upgrade for a CVE, it is much appreciated if you can have a review soon! thank you very much!

**Comment by jbertram** [comment]
@gaol, Clebert is on PTO this week. I'll go ahead and merge this as it looks good to me.

**Pull request merged**
