### PR TITLE
(7.4.z) ENTMQBR-8122 - Unhandled NullPointerException in JournalTransaction::forget

### PR DESCRIPTION
**Pull request by soul2zimate**
JBEAP issue: https://issues.redhat.com/browse/JBEAP-24947

LTS EAP ENTMQBR issue: https://issues.redhat.com/browse/ENTMQBR-8122

Upstream issue: https://issues.apache.org/jira/browse/ARTEMIS-4302

Upstream PR: https://github.com/apache/activemq-artemis/pull/4499

downstream: ENTMQBR-8122

Make this as draft to avoid being merged before we start EAP 7.4.13 process.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
this looks good to me

**Comment by soul2zimate** [comment]
Please don't merge this to `2.16.0.jbossorg-eap-x` branch. This is for EAP 7.4.13.
 
We have Artemis upgraded in EAP 7.4.12 which is in testing scope. I want keep `2.16.0.jbossorg-eap-x` untouched until 7.4.12 sign-off.

**Comment by soul2zimate** [comment]
Hi @brusdev Lin is taking care of the release coordination for next CP. I will defer this question to him.

@gaol, Do you want this get merged ?

**Comment by gaol** [comment]
Thank you @soul2zimate 

Yes, Please. @brusdev

**Comment by brusdev** [comment]
@gaol no problem, PR merged.

**Pull request merged**
